### ISSUE TITLE
Issue with HttpService.get() when empty config object supplied

### ISSUE THREAD

**Issue by jeffmath** [greencatsoft/scalajs-angular#102]
Hello,
Is there a reason why, when I supply an HttpConfig.empty object to a HttpService.get() call, the value supplied to my success() callback is no longer a js.Object, but is rather a string of unparsed JSON?  The call to HttpService.get() with no config object supplies the success() callback with the js.Object I am expecting.  But I need to add the config object so I can eventually provide an authorization header.
Thanks in advance for your help.

**Comment by jeffmath** [comment]
I think I've found the problem, which also affects the other methods of HttpService where an HttpConfig object is supplied.  HttpConfig.empty creates empty arrays for its transformRequest and transformResponse fields, which overwrite the default transformations for requests and responses, as stated [here](https://docs.angularjs.org/api/ng/service/$http#overriding-the-default-transformations-per-request).  In my opinion, HttpConfig.empty should add the default transformations to the transformRequest and transformResponse arrays, using the manner described in the link, to match what I think would be the normal expectation of the programmer, which is that serialization to and from JSON will occur as it usually does.

**Comment by mysticfall** [comment]
I just added a builder API to construct `HttpConfig` more easily:
```scala
HttpConfig(http.defaults).method("GET").url("/").build
```
Note that I didn't changed the implementation of `HttpConfig.empty`, because we can't add default transformers within that method without any reference to `$http`.

Please see if this change can meet your requirements, and let me know if it needs further enhancements.

Thanks!

**Comment by jeffmath** [comment]
The new builder works great.  Thanks for the fix!

**Comment by mysticfall** [comment]
Glad to know that it helped :)
