### ISSUE TITLE
HttpService.delete() methods have incorrect parameters?

### ISSUE THREAD

**Issue by jeffmath** [greencatsoft/scalajs-angular#103]
The methods are:

`def delete[T](url: String): HttpPromise[T] = js.native`
`def delete[T](url: String, data: js.Any): HttpPromise[T] = js.native`
`def delete[T](url: String, data: js.Any, config: HttpConfig): HttpPromise[T] = js.native`

But according to the AngularJS [doc](https://docs.angularjs.org/api/ng/service/$http#delete), shouldn't they be?:

`def delete[T](url: String): HttpPromise[T] = js.native`
`def delete[T](url: String, config: HttpConfig): HttpPromise[T] = js.native`

**Comment by mysticfall** [comment]
Oh... you are right. It seems I was rather careless in copying & pasting from similar methods :stuck_out_tongue_winking_eye:

I'll publish a new version with the fix now. Thanks for bringing this to my notice!
