### ISSUE TITLE
Json deserialization

### ISSUE THREAD

**Issue by vasigorc** [greencatsoft/scalajs-angular#108]
Hello and thank you for the scalajs-angular endeavor. 

I want to try a small project using your library, however the small question that I have will probably be unrelated to that.

When in the tutorial you write ` val future: Future[User] = http.get("/users/john")` how are you deserializing the Json string into a Scalajs object?

Thank you

**Comment by mysticfall** [comment]
Hi, I'm using _uPickle_ for my project, and used _Prickle_ before too, and both of them worked quite well with this project.

Please let me know if you need further help. Thanks!

**Comment by vasigorc** [comment]
That's neat. Thanks. I probably will as I advance with my project.
