### ISSUE TITLE
Why link function has 4 args (why controllers?)

### ISSUE THREAD

**Issue by Sergey80** [greencatsoft/scalajs-angular#32]
Why does link function contain 4th arg, controllers ?
`def link(scope: ScopeType, elems: Seq[Element], attrs: Attributes, controllers: Controller*`

As I can see Angular link function contains 3 args:

`function link(scope, element, attrs) { ... }`

https://docs.angularjs.org/guide/directive

**Comment by mysticfall** [comment]
Please check the last example shown in the documentation you've linked :)

**Comment by Sergey80** [comment]
it is interesting.. :) Thanks.
