### ISSUE TITLE
Html5 Mode for RouteProvider

### ISSUE THREAD

**Issue by giovannicandido** [greencatsoft/scalajs-angular#35]
Following AngularJS API the route provider has a method to configure html5 link mode:

https://docs.angularjs.org/api/ngRoute/service/$route

```
$locationProvider.html5Mode(true);
```

**Comment by mysticfall** [comment]
Sorry if I didn't understand the requirement correctly, but I don't know how ```$locationProvider``` and ```$route``` are related to each other regarding the ```html5Mode``` function.

We already have ```html5Mode``` API available in the ```LocationProvider``` trait (I just added a helper object to facilitate instantiation the ```Html5ModeInfo``` trait), but I'm not sure what needs to be done with ```Route``` or ```RouteProvider``` traits.

Could you elaborate more on this one, please?

**Comment by giovannicandido** [comment]
I just try to configure the html5Mode in the locationProvider injected in the RouterConfig, because I follow the angularjs documentation, as it was no method in the object I assume that it was not ported. The documentation in Angular as well in scalajs-angular is not clear on how to enable this.

**Comment by giovannicandido** [comment]
@mysticfall Thanks, I'm injection the locationProvider and configuring from that, the helper object in routerConfig is also a good thing.
