### ISSUE TITLE
Availability of 0.5?

### ISSUE THREAD

**Issue by kkasravi** [greencatsoft/scalajs-angular#51]
We would like to use 0.5-SNAPSHOT but recent changes (Promise[T]) caused some breakage. Any idea when 0.5 will be released?

**Comment by math85360** [comment]
Hi,

Promise type has just changed to have correct typed future when you get your result.
It's more in spirit of Scala with strong-typing everywhere.

I think you could use Promise[_] if you don't want typed promise but it's better for your code to use Promise[T] with T as the right type.

If you think in specific cases it's not needed, please provide more details.

Thanks

**Comment by mysticfall** [comment]
Yes, we had to introduce some changes which has broken backward compatibility (for a good reason, I hope), so I was thinking about making a new release as soon as it's tested to be working correctly.

Currently, I'm fixing minor problems with the changes, so it won't take too long before the release.

**Comment by kkasravi** [comment]
thanks for the update. We are looking forward to the 0.5 release and i found the SNAPSHOT to be very good.

**Comment by kkasravi** [comment]
Feel free to close this issue (question).

**Comment by mysticfall** [comment]
Just released version 0.5. Please let me know if you find any problem. Thanks!
