### ISSUE TITLE
ModalService: how to pass resolve into the controller?

### ISSUE THREAD

**Issue by Alex-Ikanow** [greencatsoft/scalajs-angular#68]
Apologies if this is obvious..

I have successfully launched a modal with its own controller via ModalService/ModalOptions, and then the controller has used ModaIInstance to close the modal.

I am now trying to pass parameters into the controller via the resolve parameter in ModalOptions, but I can't see how to retrieve it anywhere? In angularjs it gets injected into the controller "function" but scala.js does not seem to support this construct.

How do you intend for parameters to be passed in? Thanks!

(For reference, relevant code is:
* launching the modal: https://github.com/Alex-Ikanow/aleph2_bucket_builder/blob/97cd0d63569ab8f43284aa93e582e07523c45c49/src/main/scala/com/ikanow/aleph2/builder_ui/controllers/BucketBuilderController.scala#L104
* the modal controller: https://github.com/Alex-Ikanow/aleph2_bucket_builder/blob/97cd0d63569ab8f43284aa93e582e07523c45c49/src/main/scala/com/ikanow/aleph2/builder_ui/controllers/FormBuilderController.scala
)

**Comment by mysticfall** [comment]
You can inject resolve parameters to the constructor of your controller instance, just like any other dependencies.

In order for this to work, the name and type of the constructor variable should be compatible with those passed in the resolve parameters.

Please let me know if you find any problem. Sorry for the very late response!

**Comment by Alex-Ikanow** [comment]
Thanks for the reply! So here's an example of what I'm doing that's failing, perhaps you can point out my (probably obvious!) mistake:

I'm calling the modal like this:

```
  		  modal.open(
  				  js.Dynamic.literal(
  						  templateUrl = "templates/form_builder.html",
  						  controller = "formBuilderCtrl", 
  						  backdrop = "static",
  						  size = size,
  						  resolve = js.Dynamic.literal(
  						      test_param = "TEST_PARAM"
  						      )
  						      .asInstanceOf[js.Dictionary[js.Any]]
  						  )
  						  .asInstanceOf[ModalOptions]
  				  )
```
and then my controller constructor looks like this:

```
@injectable("formBuilderCtrl")
class FormBuilderController(
    scope: FormBuilderScope,
    root_scope: RootScope,
    element_service: ElementService,
    undo_redo_service: UndoRedoService,
    json_gen_service: JsonGenerationService,
    modal: ModalInstance[Unit],
    test_param: js.Any
    )
    
  extends AbstractController[Scope](scope) {

  /**/
  println("TEST_PARAM= " + test_param);
  
```

and test_param is undefined

**Comment by Alex-Ikanow** [comment]
Ah I have it! Sorry I hadn't realized that resolve had to be a dictionary of functions, I'm new to Angular.

For any interested parties reading, this worked:

```
  		  modal.open(
  				  js.Dynamic.literal(
  						  templateUrl = "templates/form_builder.html",
  						  controller = "formBuilderCtrl", 
  						  backdrop = "static",
  						  size = size,
  						  resolve = js.Dynamic.literal(
  						      test_param = () => "TEST_PARAM"
  						      )
  						      .asInstanceOf[js.Dictionary[js.Any]]
  						  )
  						  .asInstanceOf[ModalOptions]
  				  )
```

(should resolve have type `js.Dictionary[js.Function0[js.Any]]` to make this clearer?)

**Comment by mysticfall** [comment]
Glad to know that you made it working now. And I changed the return type to reflect the API more precisely as you suggested. Thanks!
