### ISSUE TITLE
How to use HttpInterceptor?

### ISSUE THREAD

**Issue by axos88** [greencatsoft/scalajs-angular#88]
Hello,

Please provide docs or an example on how to use HttpInjector
```
@injectable("myInterceptor")
class MyInterceptor extends ????????? {
  override def request(config: HttpConfig) = { 
    dom.window.console.log("Sending request... ", config); 
    config 
  }
}

class FooConfig(httpProvider: HttpProvider) extends Config {
  httpProvide.interceptors.push(Angular.nameOf[MyInterceptor]) ???
}
```

**Comment by mysticfall** [comment]
You'll need to extend `HttpInterceptor` trait and register it using `HttpInterceptorFactory`.

The factory expect to produce a javascript function, but it provides an implicit conversion from `HttpInterceptor` to the expected type, so you can just instantiate and return it.

Sorry for the late answer. Please let me know if you need any further help.

**Comment by axos88** [comment]
Figured it out in the meantime. Maybe it's something worth adding to the example project

**Comment by mysticfall** [comment]
I definitely agree that the project needs both examples and tests. I'm just too occupied with my current project right now to work on it right now. I hope I would find more free time soon.

I'll close the issue for now, please feel free to reopen it if further discussion is needed.
